version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  release-build:
    working_directory: ~/rust-build
    docker:
      - image: cimg/base:edge-20.04
    environment:
      TERM: dumb
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build docker image
          command: docker build -f Dockerfile -t spectare/rust-build:latest .
      - run:
          name: Push rust-build image to docker hub
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker tag spectare/rust-build:latest spectare/rust-build:$CIRCLE_TAG
            docker push spectare/rust-build:$CIRCLE_TAG
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  ci:
    jobs:
      - release-build:
          context: DOCKER
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
